export type PixelArtCategory =
  | 'Pixel Pups'
  | 'Pixel Kittens'
  | 'Pixel Fun'
  | 'Community Redeems'
  | 'Icons & Effects'
  | 'Game Sprites'
  | 'Emotes';

export const PIXEL_ART_CATEGORIES: PixelArtCategory[] = [
  'Pixel Pups',
  'Pixel Kittens',
  'Pixel Fun',
  'Community Redeems',
  'Icons & Effects',
  'Game Sprites',
  'Emotes',
];

export interface PixelArt {
  id: string;
  name: string;
  category: PixelArtCategory;
  src: string;
  animated: boolean;
}

export const pixelArt: PixelArt[] = [
  { id: 'chihuahua-girl', name: 'Chihuahua Girl', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0001-ChihuahuaGirlv1.gif', animated: true },
  { id: 'delilah', name: 'Delilah', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0003-Delilah.gif', animated: true },
  { id: 'danny', name: 'Danny', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0004-Danny.gif', animated: true },
  { id: 'danny-side-eye', name: 'Danny (Side-eye)', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0004-DannySideeye.gif', animated: true },
  { id: 'danny-swanky', name: 'Danny (Swanky)', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0004-DannySwanky.gif', animated: true },
  { id: 'poppy-momo', name: 'Poppy & Momo', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0005-PoppyAndMomo.gif', animated: true },
  { id: 'dakota', name: 'Dakota', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0006-Dakota.gif', animated: true },
  { id: 'izzy', name: 'Izzy', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0007-Izzy.gif', animated: true },
  { id: 'frank', name: 'Frank', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0008-Frank.gif', animated: true },
  { id: 'rocky', name: 'Rocky', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0009-Rocky.gif', animated: true },
  { id: 'obie', name: 'Obie', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0010-Obie.gif', animated: true },
  { id: 'cloud', name: 'Cloud', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0011-Cloud.gif', animated: true },
  { id: 'doogan', name: 'Doogan', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0012-Doogan.gif', animated: true },
  { id: 'ronnie', name: 'Ronnie', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0013-Ronnie.gif', animated: true },
  { id: 'ginger', name: 'Ginger', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0014-Ginger.gif', animated: true },
  { id: 'chula', name: 'Chula', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0015-Chula.gif', animated: true },
  { id: 'dooly', name: 'Dooly', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0016-Dooly.gif', animated: true },
  { id: 'dolly-parton', name: 'Dolly Parton', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0017-DollyParton.gif', animated: true },
  { id: 'louis', name: 'Louis', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0018-Louis.gif', animated: true },
  { id: 'summit', name: 'Summit', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0019-Summit.gif', animated: true },
  { id: 'gracie', name: 'Gracie', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0020-Gracie.gif', animated: true },
  { id: 'faith', name: 'Faith', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0021-Faith.gif', animated: true },
  { id: 'buster-brown', name: 'Buster Brown', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0022-BusterBrown.gif', animated: true },
  { id: 'cally', name: 'Cally', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0023-Cally.gif', animated: true },
  { id: 'lucky', name: 'Lucky', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0024-Lucky.gif', animated: true },
  { id: 'tucker', name: 'Tucker', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0025-Tucker.gif', animated: true },
  { id: 'bane', name: 'Bane', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0026-Bane.gif', animated: true },
  { id: 'nitrox', name: 'Nitrox', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0027-Nitrox.gif', animated: true },
  { id: 'fiona', name: 'Fiona', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0028-Fiona.gif', animated: true },
  { id: 'coco', name: 'Coco', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0029-Coco.gif', animated: true },
  { id: 'athena', name: 'Athena', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0030-Athena.gif', animated: true },
  { id: 'rocha', name: 'Rocha', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0031-Rocha.gif', animated: true },
  { id: 'nanuka', name: 'Nanuka', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0032-Nanuka.gif', animated: true },
  { id: 'sadie', name: 'Sadie', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0033-Sadie.gif', animated: true },
  { id: 'tina', name: 'Tina', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0034-Tina.gif', animated: true },
  { id: 'nacho', name: 'Nacho', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0035-Nacho.gif', animated: true },
  { id: 'joey', name: 'Joey', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0036-Joey.gif', animated: true },
  { id: 'raincoat-pup', name: 'Raincoat Pup', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0037-RaincoatPup.gif', animated: true },
  { id: 'lily-jack', name: 'Lily & Jack', category: 'Pixel Pups', src: '/assets/pixel-art/pixel-pups/0038-LilyAndJack.gif', animated: true },

  { id: 'scatdi-pebbi', name: 'Scatdi Pebbi', category: 'Pixel Kittens', src: '/assets/pixel-art/pixel-kittens/0001-Scatdi-Pebbi.gif', animated: true },
  { id: 'zo', name: 'Zo', category: 'Pixel Kittens', src: '/assets/pixel-art/pixel-kittens/0002-Zo-12_Feet_Up.gif', animated: true },
  { id: 'figgie', name: 'Figgie', category: 'Pixel Kittens', src: '/assets/pixel-art/pixel-kittens/0003-Figgie-StephenBallBall.gif', animated: true },

  { id: 'bush-shiba', name: 'Bush Shiba', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0001-BushShiba.gif', animated: true },
  { id: 'pedro-the-raccoon', name: 'Pedro the Raccoon', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0004-PedroGingerRaccoon.gif', animated: true },
  { id: 'yusuf-dikec', name: 'Yusuf Dikec', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0005-YusufDikec.gif', animated: true },
  { id: 'baby-yoda', name: 'Baby Yoda', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0006-BabyYoda.gif', animated: true },
  { id: 'apt-dance', name: 'APT Dance', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0007-APT.gif', animated: true },
  { id: 'cozy-silhouette-1', name: 'Cozy Silhouette 1', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0008-CozySilhouetteAnimal1.png', animated: false },
  { id: 'cozy-silhouette-2', name: 'Cozy Silhouette 2', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0008-CozySilhouetteAnimal2.png', animated: false },
  { id: 'cozy-silhouette-3', name: 'Cozy Silhouette 3', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0008-CozySilhouetteAnimal3.png', animated: false },
  { id: 'cozy-silhouette-4', name: 'Cozy Silhouette 4', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0008-CozySilhouetteAnimal4.png', animated: false },
  { id: 'bonfire', name: 'Bonfire', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0009-Bonfire5.gif', animated: true },
  { id: 'tree-silhouette-1', name: 'Tree Silhouette 1', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0010-TreeSilhouette1.png', animated: false },
  { id: 'tree-silhouette-2', name: 'Tree Silhouette 2', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0010-TreeSilhouette2.png', animated: false },
  { id: 'tree-silhouette-3', name: 'Tree Silhouette 3', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0010-TreeSilhouette3.png', animated: false },
  { id: 'tree-silhouette-4', name: 'Tree Silhouette 4', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0010-TreeSilhouette4.png', animated: false },
  { id: 'tree-silhouette-5', name: 'Tree Silhouette 5', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0010-TreeSilhouette5.png', animated: false },
  { id: 'christmas-tree', name: 'Christmas Tree', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0011-ChristmasTree.png', animated: false },
  { id: 'gift-boxes', name: 'Gift Boxes', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0012-GiftBoxes.png', animated: false },
  { id: 'easter-eggs', name: 'Easter Eggs', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0013-EasterEggs.png', animated: false },
  { id: 'bongo-cat', name: 'Bongo Cat', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/BongoCat.gif', animated: true },
  { id: 'bird-march', name: 'Bird March', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/BirdMarch.gif', animated: true },
  { id: 'fluffington', name: 'Fluffington', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/Fluffington.gif', animated: true },
  { id: 'mr-meowgi', name: 'Mr. Meowgi', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/MrMeowgi-StephenBallBall.gif', animated: true },
  { id: 'pedro-raccoon', name: 'Pedro Raccoon', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/pedro-raccoon.gif', animated: true },
  { id: 'turbo-cat', name: 'Turbo Cat', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/TurboCat.png', animated: false },
  { id: 'sprinkle-donut', name: 'Sprinkle Donut', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0003-SprinkleDonut.png', animated: false },
  { id: 'glazed-donut', name: 'Glazed Donut', category: 'Pixel Fun', src: '/assets/pixel-art/pixel-fun/0003-GlazeDonut.png', animated: false },

  { id: 'crown-princess-millie-bobby-brown', name: 'Crown Princess Millie Bobby Brown', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/CrownPrincessMillieBobbyBrown-unwepttomcat350.gif', animated: true },
  { id: 'darth-vader', name: 'Darth Vader', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/DarthVader-Critical_Donut99.gif', animated: true },
  { id: 'elliot', name: 'Elliot', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/Elliot-Megan-upwettomcat350.gif', animated: true },
  { id: 'gerbil-cuddle-puddle', name: 'Gerbil Cuddle Puddle', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/GerbilCuddlePuddle-ingen2.gif', animated: true },
  { id: 'hope', name: 'Hope', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/Hope-Megan-unwepttomcat350.gif', animated: true },
  { id: 'jasper', name: 'Jasper', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/JasperDog-DevMerlin.gif', animated: true },
  { id: 'stephenballball-logo', name: 'StephenBallBall Logo', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/Logo-StephenBallBall.gif', animated: true },
  { id: 'maple-the-doop', name: 'Maple the Doop', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/MapleTheDoop-ingen2.gif', animated: true },
  { id: 'nosferatu', name: 'Nosferatu', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/Nosferatu-StephenBallBall.gif', animated: true },
  { id: 'pascal-the-chameleon', name: 'Pascal the Chameleon', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/PascalChameleon-lilgamerchick.gif', animated: true },
  { id: 'sir-humpington-the-1st', name: 'Sir Humpington the 1st', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/SirHumpingtonThe1st-ingen2Cream.gif', animated: true },
  { id: 'tapir', name: 'Tapir', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/Tapir-emaudio-2.gif', animated: true },
  { id: 'tapir-tapirmakesgames', name: 'Tapir (TapirMakesGames)', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/Tapir-emaudio-2TapirMakesGames.gif', animated: true },
  { id: 'yoshi', name: 'Yoshi', category: 'Community Redeems', src: '/assets/pixel-art/community-redeems/Yoshi-lilgamerchick.gif', animated: true },

  { id: 'balloons', name: 'Balloons', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/BalloonsPreview.png', animated: false },
  { id: 'bubbles', name: 'Bubbles', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/BubblesPreview.png', animated: false },
  { id: 'confetti', name: 'Confetti', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/ConfettiPreview.png', animated: false },
  { id: 'extremeplosion', name: 'Extremeplosion', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/EXTREMEPLOSIONPreview.png', animated: false },
  { id: 'fireworks', name: 'Fireworks', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/FireworksPreview.png', animated: false },
  { id: 'flower-power', name: 'Flower Power', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/FlowerPowerPreview.png', animated: false },
  { id: 'group-parachute', name: 'Group Parachute', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/GroupParachutePreview.png', animated: false },
  { id: 'hearts', name: 'Hearts', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/HeartsPreview.png', animated: false },
  { id: 'heavy-rain', name: 'Heavy Rain', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/HeavyRainPreview.png', animated: false },
  { id: 'heavy-snow', name: 'Heavy Snow', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/HeavySnowPreview.png', animated: false },
  { id: 'hey-listen', name: 'Hey Listen', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/HeyListenPreview.png', animated: false },
  { id: 'holy-hail', name: 'Holy Hail', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/HolyHailPreview.png', animated: false },
  { id: 'kaboom', name: 'Kaboom', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/KaboomPreview.png', animated: false },
  { id: 'let-it-snow', name: 'Let It Snow', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/LetItSnowPreview.png', animated: false },
  { id: 'lightning', name: 'Lightning', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/LightningPreview.png', animated: false },
  { id: 'make-it-leaf', name: 'Make It Leaf', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/MakeItLeafPreview.png', animated: false },
  { id: 'make-it-rain', name: 'Make It Rain', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/MakeItRainPreview.png', animated: false },
  { id: 'parachute-drop', name: 'Parachute Drop', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/ParachuteDropPreview.png', animated: false },
  { id: 'parachute-droplets', name: 'Parachute Droplets', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/ParachuteDropletsPreview.png', animated: false },
  { id: 'quiz-party', name: 'Quiz Party', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/QuizPartyPreview.png', animated: false },
  { id: 'rainbow', name: 'Rainbow', category: 'Icons & Effects', src: '/assets/pixel-art/icons-effects/RainbowPreview.png', animated: false },

  { id: 'happy-bird', name: 'Happy Bird', category: 'Game Sprites', src: '/assets/pixel-art/game-sprites/0001-HappyBirdWalk.gif', animated: true },
  { id: 'rainbow-bird', name: 'Rainbow Bird', category: 'Game Sprites', src: '/assets/pixel-art/game-sprites/0001-HappyBirdRainbowFast.gif', animated: true },
  { id: 'poop', name: 'Poop', category: 'Game Sprites', src: '/assets/pixel-art/game-sprites/0007-Poop.gif', animated: true },
  { id: 'shrimpie', name: 'Shrimpie', category: 'Game Sprites', src: '/assets/pixel-art/game-sprites/0011-Shrimpie.png', animated: false },
  { id: 'ghostie', name: 'Ghostie', category: 'Game Sprites', src: '/assets/pixel-art/game-sprites/0020-Ghostie.png', animated: false },
  { id: 'pinky-the-flaminky', name: 'Pinky the Flaminky', category: 'Game Sprites', src: '/assets/pixel-art/game-sprites/PinkyTheFlaminky.png', animated: false },
  { id: 'poopy-bird-title', name: 'Poopy Bird Title', category: 'Game Sprites', src: '/assets/pixel-art/game-sprites/PoopyBirdTitle.png', animated: false },
  { id: 'blue-shrimpie', name: 'Blue Shrimpie', category: 'Game Sprites', src: '/assets/pixel-art/game-sprites/BlueShrimpie.png', animated: false },
  { id: 'shrimptopia-title', name: 'Shrimptopia Title', category: 'Game Sprites', src: '/assets/pixel-art/game-sprites/0014-ShrimptopiaTitle.png', animated: false },

  { id: 'instafluff-raccoon', name: 'Instafluff Raccoon', category: 'Emotes', src: '/assets/pixel-art/emotes/instafRaccoon4x.gif', animated: true },
  { id: 'instafluff-thank-you', name: 'Instafluff Thank You', category: 'Emotes', src: '/assets/pixel-art/emotes/instafTY4x.png', animated: false },
];