title: Instafluff
author: Instafluff
email: instaflufftv@gmail.com
name: Instafluff
description: Comfiest Action/Adventure Quickplays and Speedruns Wed/Thu/Fri 9am PST on Twitch.TV

social_sites:
  twitch: instafluff
  twitter: instaflufftv
  instagram: instaflufftv
  youtube: instaflufftv

markdown: kramdown

theme: jekyll-theme-minimal
